### ISSUE TITLE
it crash when I try to load world with Fabric 1.16.5

### ISSUE THREAD

**Issue by ROTCTHSPECIAL** [tr7zw/FirstPersonModel#252]
---- Minecraft Crash Report ----
// Don't do that.

Time: 14/3/2565, 14:31 น.
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at dev.tr7zw.skinlayers.SkinUtil.getSkinTexture(SkinUtil.java:23)
	at dev.tr7zw.skinlayers.renderlayers.HeadLayerFeatureRenderer.setupModel(HeadLayerFeatureRenderer.java:73)
	at dev.tr7zw.skinlayers.renderlayers.HeadLayerFeatureRenderer.render(HeadLayerFeatureRenderer.java:58)
	at dev.tr7zw.skinlayers.renderlayers.HeadLayerFeatureRenderer.method_4199(HeadLayerFeatureRenderer.java:30)
	at net.minecraft.class_922.method_4054(class_922.java:204)
	at net.minecraft.class_1007.method_4215(class_1007.java:65)
	at net.minecraft.class_1007.method_3936(class_1007.java:42)
	at net.minecraft.class_898.method_3954(class_898.java:311)
	at net.minecraft.class_761.method_22977(class_761.java:2120)
	at net.minecraft.class_761.handler$bac000$render(class_761.java:4123)
	at net.minecraft.class_761.method_22710(class_761.java:1752)
	at net.minecraft.class_757.method_3188(class_757.java:1022)
	at net.minecraft.class_757.method_3192(class_757.java:693)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dev.tr7zw.skinlayers.SkinUtil.getSkinTexture(SkinUtil.java:23)
	at dev.tr7zw.skinlayers.renderlayers.HeadLayerFeatureRenderer.setupModel(HeadLayerFeatureRenderer.java:73)
	at dev.tr7zw.skinlayers.renderlayers.HeadLayerFeatureRenderer.render(HeadLayerFeatureRenderer.java:58)
	at dev.tr7zw.skinlayers.renderlayers.HeadLayerFeatureRenderer.method_4199(HeadLayerFeatureRenderer.java:30)
	at net.minecraft.class_922.method_4054(class_922.java:204)
	at net.minecraft.class_1007.method_4215(class_1007.java:65)
	at net.minecraft.class_1007.method_3936(class_1007.java:42)

-- Entity being rendered --
Details:
	Entity Type: minecraft:player (net.minecraft.class_746)
	Entity ID: 131
	Entity Name: Kuroda_Takeshi
	Entity's Exact location: 195.56, 63.00, -77.70
	Entity's Block location: World: (195,63,-78), Chunk: (at 3,3,2 in 12,-5; contains blocks 192,0,-80 to 207,255,-65), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_1007@7d205910
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: -231.98381
	Delta: 0.0
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:311)
	at net.minecraft.class_761.method_22977(class_761.java:2120)
	at net.minecraft.class_761.handler$bac000$render(class_761.java:4123)
	at net.minecraft.class_761.method_22710(class_761.java:1752)
	at net.minecraft.class_757.method_3188(class_757.java:1022)

-- Affected level --
Details:
	All players: 1 total; [class_746['Kuroda_Takeshi'/131, l='ClientLevel', x=195.56, y=63.00, z=-77.70]]
	Chunk stats: Client Chunk Cache: 441, 238
	Level dimension: minecraft:overworld
	Level spawn location: World: (189,71,-157), Chunk: (at 13,4,3 in 11,-10; contains blocks 176,0,-160 to 191,255,-145), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 12251 game time, 12251 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:617)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:699)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2070171896 bytes (1974 MB) / 3154116608 bytes (3008 MB) up to 3154116608 bytes (3008 MB)
	CPUs: 8
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmn128M -Xmx3000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		alaskanativecraft: Alaska Native Craft 1.2.2
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		autopath: Automatic Path 1.4.3
		betterdroppeditems: Better Dropped Items 1.2.4-1.16.2
		bewitchment: Bewitchment 1.16.5-18
		cardinal-components-base: Cardinal Components API (base) 2.8.2
		cardinal-components-entity: Cardinal Components API (entities) 2.8.2
		cardinal-components-item: Cardinal Components API (items) 2.7.2
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config2: Cloth Config v4 4.14.54
		cosmetic-armor: Cosmetic Armor 1.0.0
		cpas: conveniently placed armor slots 1.3.0+1.16.5
		curios: Curios API 0.0.13-1.16.5
		fabric: Fabric API 0.42.0+1.16
		fabric-api-base: Fabric API Base 0.4.0+3cc0f0907d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+3cc0f0907d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.13+3cc0f0907d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+3cc0f0907d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+3cc0f0907d
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+3cc0f0907d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+3cc0f0907d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.5+3cc0f0907d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.4+3cc0f0907d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.8+3cc0f0907d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.4+3cc0f0907d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.5+3cc0f0907d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+3cc0f0907d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+3cc0f0907d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.2+3cc0f0907d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+3cc0f0907d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+3cc0f0907d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+3cc0f0907d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.2+3cc0f0907d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.3+3cc0f0907d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.4+3cc0f0907d
		fabric-models-v0: Fabric Models (v0) 0.3.1+3cc0f0907d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.5+3cc0f0907d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.9+3cc0f0907d
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+3cc0f0907d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.6+3cc0f0907d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+3cc0f0907d
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+3cc0f0907d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.6+3cc0f0907d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+3cc0f0907d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.5+3cc0f0907d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.1+3cc0f0907d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+3cc0f0907d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.15+3cc0f0907d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.3+3cc0f0907d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.1+3cc0f0907d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+3cc0f0907d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.1+3cc0f0907d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.6+3cc0f0907d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+3cc0f0907d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.2+3cc0f0907d
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+3cc0f0907d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.8+3cc0f0907d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.0+3cc0f0907d
		fabricloader: Fabric Loader 0.13.3
		fiber: fiber 0.23.0-2
		firstperson: FirstpersonModel 2.0.2
		geckolib3: Geckolib 3.0.68
		graveyard: The Graveyard 1.1
		impersonate: Impersonate 2.2.1
		java: Java HotSpot(TM) 64-Bit Server VM 8
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		kirin: Kirin UI 1.7-1.16.2
		mermod: Mermod 1.7
		minecraft: Minecraft 1.16.5
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 1.16.22
		notenoughanimations: NotEnoughAnimations 1.2.4
		omega-config: OmegaConfig 1.0.4
		optifabric: OptiFabric 1.12.10
		patchouli: Patchouli 1.16.4-53-FABRIC
		pehkui: Pehkui 2.6.0+1.14.4-1.18
		playerabilitylib: Pal 1.2.1
		presencefootsteps: Presence Footsteps r29+1.16.4
		primalwinter: Primal Winter 1.1.1
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		skinlayers: 3d Skin Layers 1.1.0
		somnus: Somnus API 0.0.12-1.16.5
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.4
		tlskincape: TLSkinCape 1.19
		transliterationlib: TRansliterationLib 1.0.4
		trinkets: Trinkets 2.6.7
		wildfire_gender: Wildfire's Female Gender Mod 2.8.1
	Patchouli open book context: n/a
	Launched Version: Fabric 1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1650 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 511.79, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
	OptiFine Version: OptiFine_1.16.5_HD_U_G8
	OptiFine Build: 20210515-161946
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 511.79
	OpenGlRenderer: NVIDIA GeForce GTX 1650 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.16.5
	OptiFine jar version: OptiFine_1.16.5_HD_U_G8
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Users/Lenovo/AppData/Roaming/.minecraft/.optifine/OptiFine_1.16.5_HD_U_G8/Optifine-mapped.jar
	OptiFabric error: <None>

**Comment by tr7zw** [comment]
TLauncher is not supported. Buy the game.
