### ISSUE TITLE
[fabric-2.2.3-mc1.18.2]Client crash

### ISSUE THREAD

**Issue by hsw20060929** [tr7zw/FirstPersonModel#358]
An error occurred when I tried to install this module, but it was removed and returned to normal
LOG:
[18:46:32] [Render thread/ERROR]: Mixin apply for mod identity failed identity.mixins.json:ShadowMixin from mod identity -> net.minecraft.class_898: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Variable modifier target for net/minecraft/class_898::adjustShadowSize was removed by another injector [INJECT Applicator Phase -> identity.mixins.json:ShadowMixin from mod identity -> Apply Injections ->  -> Inject -> identity.mixins.json:ShadowMixin from mod identity->@ModifyVariable::adjustShadowSize(F)F]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Variable modifier target for net/minecraft/class_898::adjustShadowSize was removed by another injector [INJECT Applicator Phase -> identity.mixins.json:ShadowMixin from mod identity -> Apply Injections ->  -> Inject -> identity.mixins.json:ShadowMixin from mod identity->@ModifyVariable::adjustShadowSize(F)F]
	at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector.inject(ModifyVariableInjector.java:169) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1377) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) [fabric-loader-0.14.20.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.14.20.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.14.20.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) [fabric-loader-0.14.20.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) [?:?]
	at net.minecraft.class_310.<init>(class_310.java:557) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:197) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.20.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.20.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.20.jar:?]
MODS:
[18:45:47] [main/INFO]: Loading 195 mods:
	- advanced_runtime_resource_pack 0.5.7
	- advancementinfo 1.18.2-fabric0.47.10-1.3.1
	- animatica 0.5+1.18.2
	- appleskin 2.4.1+mc1.18.2
	- architectury 4.11.93
	- armorchroma 1.2.1
	- autofish 0.9.4
	- badpackets 0.1.3
	- betterthanmending 1.3.0
	- boatiview 0.0.3
	- bowinfinityfix rv11
	- can-i-mine-this-block 1.2.0
	- capes 1.3.1+1.18.2
	   \-- omega-config 1.2.3-1.18.1
	- carpet 1.4.69
	- carpet-extra 1.4.72
	- cem 0.7.1
	- chat-up 2.0
	- chat_heads 0.6.0
	- citresewn 1.0.1+1.18.2
	   \-- citresewn-defaults 1.0.1+1.18.2
	- clear-skies 2.0.92
	- cloth-api 3.2.64
	   |-- cloth-client-events-v0 3.2.64
	   |-- cloth-common-events-v1 3.2.64
	   |-- cloth-datagen-api-v1 3.2.64
	   |-- cloth-scissors-api-v1 3.2.64
	   \-- cloth-utils-v1 3.2.64
	- cloth-config 6.4.90
	   \-- cloth-basic-math 0.6.1
	- collective 6.55
	- colormatic 3.1.1+mc.1.18.2
	- completeconfig 1.4.1
	- continuity 2.0.2+1.18.2
	- controlling 9.0+23
	- cool_elytra 1.3.1
	   \-- midnightlib 0.3.1
	- customskinloader 14.16
	- customwindowtitle 1.1.1
	- debugify 1.11.0
	- diggusmaximus 1.5.6-1.18
	   \-- kyrptconfig 1.4.6-1.18
	        \-- blue_endless_jankson 1.2.1
	- durabilityviewer 1.18.2-fabric0.47.10-1.10.3
	   |-- crowdin-translate 1.4+1.18.2
	   \-- gbfabrictools 1.3.4+1.18.2
	- dynamicfps 2.1.0
	   \-- com_moandjiezana_toml_toml4j 0.7.2
	- easiervillagertrading 1.18.2-fabric0.47.10-1.5.4
	   \-- gbfabrictools 1.3.4+1.18.2
	- editsign 2.3.1
	- elytratrinket 3.0.0-1.18.1
	- endportalrecipe 5.0
	- enhanced_attack_indicator 1.0.3+1.18
	- enhancedblockentities 0.7.1+1.18.2
	   \-- spruceui 3.3.0+1.17
	        \-- org_aperlambda_lambdajcommon 1.8.1
	- entity_texture_features 4.3.1
	   \-- org_apache_httpcomponents_httpmime 4.5.10
	- exordium 1.0.1-mc1.18.2
	- fabric-api 0.76.0+1.18.2
	   |-- fabric-api-base 0.4.5+64b7c69360
	   |-- fabric-api-lookup-api-v1 1.6.3+2373a54560
	   |-- fabric-biome-api-v1 8.0.7+e83becad60
	   |-- fabric-block-api-v1 1.0.0+ee3621fc60
	   |-- fabric-blockrenderlayer-v1 1.1.13+3ac43d9560
	   |-- fabric-command-api-v1 1.1.10+d7c144a860
	   |-- fabric-commands-v0 0.2.9+b4f4f6cd60
	   |-- fabric-containers-v0 0.1.24+d7c144a860
	   |-- fabric-content-registries-v0 3.1.3+c85f2e3860
	   |-- fabric-convention-tags-v1 1.1.0+43ce63a460
	   |-- fabric-crash-report-info-v1 0.2.1+ee261a3e60
	   |-- fabric-data-generation-api-v1 3.1.0+6c70b68e60
	   |-- fabric-dimensions-v1 2.1.21+489d6f8260
	   |-- fabric-entity-events-v1 1.4.9+d7c144a860
	   |-- fabric-events-interaction-v0 0.4.20+d7c144a860
	   |-- fabric-events-lifecycle-v0 0.2.22+d7c144a860
	   |-- fabric-game-rule-api-v1 1.0.13+d7c144a860
	   |-- fabric-item-api-v1 1.6.2+8165403660
	   |-- fabric-item-groups-v0 0.3.16+91896a4960
	   |-- fabric-key-binding-api-v1 1.0.12+54e5b2ec60
	   |-- fabric-keybindings-v0 0.2.10+b4f4f6cd60
	   |-- fabric-lifecycle-events-v1 2.1.1+cc71601c60
	   |-- fabric-loot-api-v2 1.1.2+1997ad1260
	   |-- fabric-loot-tables-v1 1.1.4+e747827960
	   |-- fabric-mining-level-api-v1 2.1.6+cc71601c60
	   |-- fabric-models-v0 0.3.7+d7c144a860
	   |-- fabric-networking-api-v1 1.0.24+2d30af4b60
	   |-- fabric-networking-v0 0.3.11+b4f4f6cd60
	   |-- fabric-object-builder-api-v1 2.1.5+032c981d60
	   |-- fabric-particles-v1 0.2.13+526dc1ac60
	   |-- fabric-registry-sync-v0 0.9.12+bb2e047760
	   |-- fabric-renderer-api-v1 0.5.0+bf48649860
	   |-- fabric-renderer-indigo 0.6.1+03e2b68760
	   |-- fabric-renderer-registries-v1 3.2.12+b4f4f6cd60
	   |-- fabric-rendering-data-attachment-v1 0.3.9+ee3621fc60
	   |-- fabric-rendering-fluids-v1 2.0.3+54e5b2ec60
	   |-- fabric-rendering-v0 1.1.14+b4f4f6cd60
	   |-- fabric-rendering-v1 1.10.8+54e5b2ec60
	   |-- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660
	   |-- fabric-resource-loader-v0 0.5.3+047a5ecb60
	   |-- fabric-screen-api-v1 1.0.11+d882b91560
	   |-- fabric-screen-handler-api-v1 1.2.3+1f6558e860
	   |-- fabric-textures-v0 1.0.13+3ac43d9560
	   |-- fabric-transfer-api-v1 1.6.4+f4563ac860
	   \-- fabric-transitive-access-wideners-v1 1.1.0+e747827960
	- fabric-language-kotlin 1.9.4+kotlin.1.8.21
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.21
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.20.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.0
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.0
	- fabricloader 0.14.20
	- firstperson 2.2.3
	- fixusername 1.0.0
	- grindenchantments 1.6.4+1.18.2
	- horseinfo 0.4.1-1.18
	- ias 8.0.1
	- identity 2.3.1-1.18.2
	   \-- omega-config 1.2.3-1.18.1
	- immediatelyfast 1.1.12
	   |-- com_github_llamalad7_mixinextras 0.1.1
	   \-- net_lenni0451_reflect 1.1.0
	- indium 1.0.7+mc1.18.2
	- infinitetrading 4.0
	- ingameime 1.6.5
	- inventoryprofilesnext 1.10.2
	- invmove 0.8.3
	- iris 1.6.2
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- itemmodelfix 1.0.3+1.18
	- itemscroller 0.16.1
	- java 18
	- lambdynlights 2.1.0+1.17
	   |-- pride 1.1.0+1.17
	   \-- spruceui 3.3.0+1.17
	        \-- org_aperlambda_lambdajcommon 1.8.1
	- lazydfu 0.1.2
	- libipn 3.0.1
	- litematica 0.11.6
	- lithium 0.10.3
	- magiclib 0.7.329+ed83ba7-beta
	   \-- magiclib-1_18_2 0.7.329+ed83ba7-beta
	- malilib 0.12.1
	- masa_gadget_mod 3.2.306+058f891-beta
	   \-- masa_gadget_mod-1_18_2 3.2.306+058f891-beta
	- mcwifipnp 1.6.2
	- minecraft 1.18.2
	- minihud 0.22.1
	- modmenu 3.2.5
	- moreculling 1.18.2-0.8.2
	   \-- conditional-mixin 0.3.0
	- nme 1.18.2
	- noexpensive 1.18.2-1.5.0
	- notenoughanimations 1.6.0
	- ommc 0.5-beta+ec9da71
	   \-- ommc-1_18_2 0.5-beta+ec9da71
	- phosphor 0.8.1
	- physicsmod 2.10.0
	- reeses-sodium-options 1.5.0+mc1.18.2-build.70
	- replaymod 1.18.2-2.6.12
	- roughlyenoughitems 8.3.614
	   \-- error_notifier 1.0.9
	- roughlyenoughprofessions 1.0.2
	- roughlyenoughresources 2.5.0
	- shulkerboxtooltip 3.1.3+1.18.2
	- sodium 0.4.1+build.15
	   \-- org_joml_joml 1.10.2
	- sodium-extra 0.4.18+mc1.18.2-build.98
	   |-- caffeineconfig 1.1.0+1.17
	   \-- crowdin-translate 1.4+1.18.2
	- taxfreelevels 1.3.3
	- tooltipfix 1.0.4-1.18
	- trinketofundying 2.0.2-1.18.2
	- trinkets 3.3.1
	   |-- cardinal-components-base 4.1.3
	   \-- cardinal-components-entity 4.1.3
	- tweakeroo 0.13.3
	- tweakmyclient 3.6.395+901cd91-beta
	   \-- tweakmyclient-1_18_2 3.6.395+901cd91-beta
	- viafabric 0.4.10+38-dev
	   |-- org_yaml_snakeyaml 2.0
	   |-- viafabric-mc118 0.4.10+38-dev
	   \-- viaversion 4.7.0-1.20-pre7-SNAPSHOT
	- voicechat 1.18.2-2.4.8
	- wi_zoom 1.4-MC1.18.2
	- wildfire_gender 2.9
	- worldedit 7.2.10+1742f98
	- worldeditcui 1.18.2+01
	- wthit 4.13.6
	- xaerominimap 23.4.4
	- xaeroworldmap 1.30.3

**Comment by tr7zw** [comment]
Conflict with the identity mod. Remove either, or open the identity jar, modify the mixin json in there, and remove the ``ShadowMixin`` line.
