### ISSUE TITLE
Crash when hitting f5

### ISSUE THREAD

**Issue by RodoxVR** [tr7zw/FirstPersonModel#476]
Was able to reproduce issue twice:

Was standing in snowy mountains with physics mod playing with some snow in third person when a spider came at me, 
So i quickly hit F5 to switch to first person again and it crashes.

MY MODLIST -->>
@
![minecraftmods](https://github.com/user-attachments/assets/4b808d22-20f3-445d-951c-05aeb7102b1a)

HERE IS MY CRASH LOG: -->>

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2024-07-22 20:06:27
Description: Unexpected error

java.lang.ClassCastException: class java.lang.Double cannot be cast to class java.lang.Float (java.lang.Double and java.lang.Float are in module java.base of loader 'bootstrap')
	at org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable.getReturnValueF(CallbackInfoReturnable.java:120)
	at net.minecraft.class_4184.method_19318(class_4184.java:95)
	at net.minecraft.class_4184.method_19321(class_4184.java:64)
	at net.minecraft.class_757.method_3188(class_757.java:1052)
	at net.minecraft.class_757.method_3192(class_757.java:850)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable.getReturnValueF(CallbackInfoReturnable.java:120)
	at net.minecraft.class_4184.method_19318(class_4184.java:95)
	at net.minecraft.class_4184.method_19321(class_4184.java:64)
	at net.minecraft.class_757.method_3188(class_757.java:1052)

-- Uptime --
Details:
	JVM uptime: 4646.667s
	Wall uptime: 4637.346s
	High-res time: 4634.909s
	Client ticks: 92517 ticks / 4625.850s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:905)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['King_Arroz_Doce'/27, l='ClientLevel', x=2504.51, y=69.00, z=1135.43]]
	Chunk stats: 4096, 705
	Level dimension: minecraft:overworld
	Level spawn location: World: (-580,63,1), Section: (at 12,15,1 in -37,3,0; chunk contains blocks -592,-64,0 to -577,319,15), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,-64,0 to -513,319,511)
	Level time: 161278 game time, 181668 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 144

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, betterthirdperson, blur, cloth-config, continuity, distanthorizons, eatinganimationid, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, firstperson, indium, invmove, iris, midnightlib, modmenu, noisium, notenoughanimations, physicsmod, skinlayers3d, sodium, tectonic, file/§6§lClassic 3D§c v2.0.0-A.5§e 1.21.zip, minecraft:supporteatinganimation, minecraft:physicsmod

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 3400546264 bytes (3243 MiB) / 9361686528 bytes (8928 MiB) up to 17179869184 bytes (16384 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 7800X3D 8-Core Processor           
	Identifier: AuthenticAMD Family 25 Model 97 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 2070
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 8192.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.5585
	Graphics card #1 name: AMD Radeon(TM) Graphics
	Graphics card #1 vendor: Advanced Micro Devices, Inc.
	Graphics card #1 VRAM (MiB): 512.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 31.0.22044.1
	Memory slot #0 capacity (MiB): 16384.00
	Memory slot #0 clockSpeed (GHz): 6.00
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MiB): 16384.00
	Memory slot #1 clockSpeed (GHz): 6.00
	Memory slot #1 type: Unknown
	Virtual memory max (MiB): 34973.21
	Virtual memory used (MiB): 29134.36
	Swap memory total (MiB): 3077.64
	Swap memory used (MiB): 61.39
	Space in storage for jna.tmpdir (MiB): available: 72697.92, total: 953125.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 72697.92, total: 953125.00
	Space in storage for io.netty.native.workdir (MiB): available: 72697.92, total: 953125.00
	Space in storage for java.io.tmpdir (MiB): available: 72697.92, total: 953125.00
	Space in storage for workdir (MiB): available: 72697.92, total: 953125.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		betterthirdperson: Better Third Person 1.9.0
		blur: Blur+ (Fabric) 4.1.0
			midnightlib: MidnightLib 1.5.7
		cloth-config: Cloth Config v15 15.0.127
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 3.0.0-beta.5+1.21
		distanthorizons: Distant Horizons 2.1.2-a
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f88390
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a790
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b559734490
		eatinganimationid: Eating Animation 1.21+1.9.72
		fabric-api: Fabric API 0.100.7+1.21
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.67+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.15+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.18+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.4.2+c111832ad1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.25+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.12+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.3+78017270d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.11+8f3583aed1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.13+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.1+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.0+ab7edbacd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.13+d1321076d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.10+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.25+5bd9f1bcd1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.3.0+0ae0b97dd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.5+48fb1586d1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f344d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.2.0+7e687b32d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.82+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.15+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8cd1
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		firstperson: FirstPerson 2.4.3
		indium: Indium 1.0.34+mc1.21
		invmove: InvMove 0.8.8
		iris: Iris 1.7.3+mc1.21
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.21
		modmenu: Mod Menu 11.0.1
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		noisium: Noisium 2.2.1+mc1.21
		notenoughanimations: NotEnoughAnimations 1.7.4
		physicsmod: Physics Mod 3.0.16
		skinlayers3d: 3d-Skin-Layers 1.6.6
		sodium: Sodium 0.5.11+mc1.21
		tectonic: Tectonic 2.4.0
		terralith: Terralith 2.5.4
	Loaded Shaderpack: Bliss-Shader-main.zip
		Profile: Custom (+8 options changed by user)
	Launched Version: fabric-loader-0.15.11-1.21
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce RTX 2070/PCIe/SSE2 GL version 3.2.0 NVIDIA 555.85, NVIDIA Corporation
	Window size: 2560x1440
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 13/13 chunks
	Resource Packs: vanilla, fabric, betterthirdperson, blur, cloth-config, continuity, distanthorizons (incompatible), eatinganimationid, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, firstperson, indium, invmove, iris, midnightlib, modmenu, noisium, notenoughanimations, physicsmod, skinlayers3d, sodium, tectonic, file/§6§lClassic 3D§c v2.0.0-A.5§e 1.21.zip, minecraft:supporteatinganimation, minecraft:physicsmod (incompatible)
	Current Language: en_us
	Locale: nl_NL
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 16x AMD Ryzen 7 7800X3D 8-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['King_Arroz_Doce'/27, l='ServerLevel[Nagasaki]', x=2504.51, y=69.00, z=1135.43]]
	Active Data Packs: vanilla, fabric, fabric-convention-tags-v2, terralith, terratonic (incompatible)
	Available Data Packs: vanilla, trade_rebalance, bundle, fabric, fabric-convention-tags-v2, terralith, terratonic (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	World Seed: 878301245224944924

**Comment by RodoxVR** [comment]
It was not this mod, it had to do with physics mod, snow in particular.
