### ISSUE TITLE
Mod conflict. Simple HUD utilities.

### ISSUE THREAD

**Issue by RDKRACZ** [tr7zw/FirstPersonModel#57]
[14:00:22] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'simple_utilities'!
	at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.7) ~[?:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabric-server-launch.jar:?]
	at net.minecraft.server.Main.main(Main:92) [intermediary-server.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27) [fabric-server-launch.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-server-launch.jar:?]
	Suppressed: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/blockrenderlayer/v1/BlockRenderLayerMap
		at com.codenamerevy.additionalbars.events.ModRegistry.registerRenderLayer(ModRegistry.java:137) ~[1.16.4-additionalbars-1.0.0.jar:?]
		at com.codenamerevy.additionalbars.events.ModRegistry.setup(ModRegistry.java:42) ~[1.16.4-additionalbars-1.0.0.jar:?]
		at com.codenamerevy.additionalbars.AdditionalBars.onInitialize(AdditionalBars.java:52) ~[1.16.4-additionalbars-1.0.0.jar:?]
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-server-launch.jar:?]
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabric-server-launch.jar:?]
		at net.minecraft.server.Main.main(Main:92) [intermediary-server.jar:?]
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
		at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
		at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-server-launch.jar:?]
		at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-server-launch.jar:?]
		at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27) [fabric-server-launch.jar:?]
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
		at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
		at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-server-launch.jar:?]
		at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-server-launch.jar:?]
		at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-server-launch.jar:?]
	Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.blockrenderlayer.v1.BlockRenderLayerMap
		at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_275]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
		at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_275]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
		at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56) ~[fabric-server-launch.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168) ~[fabric-server-launch.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
		... 21 more
	Suppressed: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/client/render/fluid/v1/FluidRenderHandler
		at com.tylervp.moreblocksmod.onInitialize(moreblocksmod.java:359) ~[moreblocksmod-0.1.1.0.jar:?]
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-server-launch.jar:?]
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabric-server-launch.jar:?]
		at net.minecraft.server.Main.main(Main:92) [intermediary-server.jar:?]
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
		at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
		at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-server-launch.jar:?]
		at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-server-launch.jar:?]
		at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27) [fabric-server-launch.jar:?]
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
		at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
		at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-server-launch.jar:?]
		at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-server-launch.jar:?]
		at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-server-launch.jar:?]
	Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.client.render.fluid.v1.FluidRenderHandler
		at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_275]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
		at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_275]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
		at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56) ~[fabric-server-launch.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168) ~[fabric-server-launch.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
		... 19 more
	Suppressed: java.lang.NoClassDefFoundError: me/shedaniel/fiber2cloth/api/Fiber2Cloth
		at com.skaggsm.treechoppermod.FabricTreeChopper$onInitialize$settings$1.<init>(FabricTreeChopper.java) ~[fabric-tree-chopper-0.6.0.jar:?]
		at com.skaggsm.treechoppermod.FabricTreeChopper$onInitialize$settings$1.<clinit>(FabricTreeChopper.java) ~[fabric-tree-chopper-0.6.0.jar:?]
		at com.skaggsm.treechoppermod.FabricTreeChopper.onInitialize(FabricTreeChopper.java:37) ~[fabric-tree-chopper-0.6.0.jar:?]
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-server-launch.jar:?]
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabric-server-launch.jar:?]
		at net.minecraft.server.Main.main(Main:92) [intermediary-server.jar:?]
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
		at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
		at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-server-launch.jar:?]
		at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-server-launch.jar:?]
		at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27) [fabric-server-launch.jar:?]
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
		at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
		at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-server-launch.jar:?]
		at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-server-launch.jar:?]
		at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-server-launch.jar:?]
	Caused by: java.lang.ClassNotFoundException: me.shedaniel.fiber2cloth.api.Fiber2Cloth
		at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_275]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
		at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_275]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
		at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56) ~[fabric-server-launch.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168) ~[fabric-server-launch.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
		... 21 more
	Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_1044
		at dev.tr7zw.firstperson.fabric.FirstPersonModelMod.onInitialize(FirstPersonModelMod.java:35) ~[FirstPersonMod-2.0.0-SNAPSHOT.jar:?]
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-server-launch.jar:?]
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabric-server-launch.jar:?]
		at net.minecraft.server.Main.main(Main:92) [intermediary-server.jar:?]
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
		at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
		at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-server-launch.jar:?]
		at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-server-launch.jar:?]
		at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27) [fabric-server-launch.jar:?]
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
		at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
		at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-server-launch.jar:?]
		at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-server-launch.jar:?]
		at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-server-launch.jar:?]
	Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1044
		at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_275]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
		at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_275]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
		at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56) ~[fabric-server-launch.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168) ~[fabric-server-launch.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
		... 19 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_304
	at net.johnvictorfs.simple_utilities.SimpleUtilities.registerKeybindings(SimpleUtilities.java:32) ~[simple-utilities-mod-2.0.2.jar:?]
	at net.johnvictorfs.simple_utilities.SimpleUtilities.onInitialize(SimpleUtilities.java:28) ~[simple-utilities-mod-2.0.2.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
	... 17 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_304
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_275]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_275]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
	at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
	at net.johnvictorfs.simple_utilities.SimpleUtilities.registerKeybindings(SimpleUtilities.java:32) ~[simple-utilities-mod-2.0.2.jar:?]
	at net.johnvictorfs.simple_utilities.SimpleUtilities.onInitialize(SimpleUtilities.java:28) ~[simple-utilities-mod-2.0.2.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
	... 17 more

**Comment by tr7zw** [comment]
Eh, there are a ton of exceptions in your stack trace that classes are missing. Are you sure you have stuff like the FabricAPI, fiber2cloth? Also, this is still serverside. Stop putting client mods into the server mods folder. In the newest build, it should be marked as a client mod, but even then it's really bad practice and will in the future cause more startup issues.
